language: objective-c
matrix:
  include:
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode8.3
cache:
  bundler: true
  cocoapods: true
  directories: []
branches:
  only:
    - master
    - devel
before_install:
  - brew update; true
  - brew outdated xctool || brew upgrade xctool; true
  - motion update --check || sudo motion update; true
  - (motion --version)
  - (ruby --version)
script:
  - bundle exec rake clean:all pod:install spec
